ipfabric_netbox/urls.py
from django.urls import include
from django.urls import path
from utilities.urls import get_model_urls

from . import views

urlpatterns = (
    # Source
    path("source/", views.IPFabricSourceListView.as_view(), name="ipfabricsource_list"),
    path(
        "source/add/", views.IPFabricSourceEditView.as_view(), name="ipfabricsource_add"
    ),
    path(
        "source/delete/",
        views.IPFabricSourceBulkDeleteView.as_view(),
        name="ipfabricsource_bulk_delete",
    ),
    path(
        "source/<int:pk>/delete/",
        views.IPFabricSourceDeleteView.as_view(),
        name="ipfabricsource_delete",
    ),
    path(
        "source/<int:pk>/", include(get_model_urls("ipfabric_netbox", "ipfabricsource"))
    ),
    path(
        "source/delete/",
        views.IPFabricSyncBulkDeleteView.as_view(),
        name="ipfabricsync_bulk_delete",
    ),
    # Snapshot
    path(
        "snapshot/",
        views.IPFabricSnapshotListView.as_view(),
        name="ipfabricsnapshot_list",
    ),
    path(
        "snapshot/delete/",
        views.IPFabricSnapshotBulkDeleteView.as_view(),
        name="ipfabricsnapshot_bulk_delete",
    ),
    path(
        "snapshot/<int:pk>/",
        include(get_model_urls("ipfabric_netbox", "ipfabricsnapshot")),
    ),
    path(
        "snapshot/<int:pk>/delete/",
        views.IPFabricSnapshotDeleteView.as_view(),
        name="ipfabricsnapshot_delete",
    ),
    path(
        "data/<int:pk>/delete",
        views.IPFabricSnapshotDataDeleteView.as_view(),
        name="ipfabricdata_delete",
    ),
    path("data/<int:pk>/", include(get_model_urls("ipfabric_netbox", "ipfabricdata"))),
    path(
        "data/delete",
        views.IPFabricSnapshotDataBulkDeleteView.as_view(),
        name="ipfabricdata_bulk_delete",
    ),
    # Sync
    path("sync/", views.IPFabricSyncListView.as_view(), name="ipfabricsync_list"),
    path("sync/add/", views.IPFabricSyncEditView.as_view(), name="ipfabricsync_add"),
    path("sync/<int:pk>/", include(get_model_urls("ipfabric_netbox", "ipfabricsync"))),
    # Branch
    path("branch/", views.IPFabricBranchListView.as_view(), name="ipfabricbranch_list"),
    path(
        "branch/<int:pk>/", include(get_model_urls("ipfabric_netbox", "ipfabricbranch"))
    ),
    # Transform Map
    path(
        "transform-map/",
        views.IPFabricTransformMapListView.as_view(),
        name="ipfabrictransformmap_list",
    ),
    path(
        "transform-map/restore/",
        views.IPFabricTransformMapRestoreView.as_view(),
        name="ipfabrictransformmap_restore",
    ),
    path(
        "transform-map/add",
        views.IPFabricTransformMapEditView.as_view(),
        name="ipfabrictransformmap_add",
    ),
    path(
        "transform-map/delete/",
        views.IPFabricTransformMapBulkDeleteView.as_view(),
        name="ipfabrictransformmap_bulk_delete",
    ),
    path(
        "transform-map/<int:pk>/",
        include(get_model_urls("ipfabric_netbox", "ipfabrictransformmap")),
    ),
    path(
        "transform-map/<int:pk>/delete/",
        views.IPFabricTransformMapDeleteView.as_view(),
        name="ipfabrictransformmap_delete",
    ),
    # Transform field
    path(
        "transform-field/",
        views.IPFabricTransformFieldListView.as_view(),
        name="ipfabrictransformfield_list",
    ),
    path(
        "transform-field/add/",
        views.IPFabricTransformFieldEditView.as_view(),
        name="ipfabrictransformfield_add",
    ),
    path(
        "transform-field/<int:pk>/",
        include(get_model_urls("ipfabric_netbox", "ipfabrictransformfield")),
    ),
    path(
        "transform-field/<int:pk>/delete/",
        views.IPFabricTransformFieldDeleteView.as_view(),
        name="ipfabrictransformfield_delete",
    ),
    # Relationship Field
    path(
        "relationship-field/",
        views.IPFabricRelationshipFieldListView.as_view(),
        name="ipfabricrelationshipfield_list",
    ),
    path(
        "relationship-field/add/",
        views.IPFabricRelationshipFieldEditView.as_view(),
        name="ipfabricrelationshipfield_add",
    ),
    path(
        "relationship-field/<int:pk>/",
        include(get_model_urls("ipfabric_netbox", "ipfabricrelationshipfield")),
    ),
    path(
        "relationship-field/<int:pk>/delete/",
        views.IPFabricRelationshipFieldDeleteView.as_view(),
        name="ipfabricrelationshipfield_delete",
    ),
)

ipfabric_netbox/models.py
import ast
import json
import logging
import traceback
from copy import deepcopy

import httpx
from core.choices import DataSourceStatusChoices
from core.exceptions import SyncError
from core.models import Job
from core.signals import pre_sync
from dcim.models import VirtualChassis
from dcim.signals import assign_virtualchassis_master
from django.apps import apps
from django.conf import settings
from django.contrib.contenttypes.models import ContentType
from django.core.cache import cache
from django.core.validators import MinValueValidator
from django.db import models
from django.db import transaction
from django.db.models import Q
from django.db.models import signals
from django.urls import reverse
from django.utils import timezone
from django.utils.module_loading import import_string
from django.utils.translation import gettext as _
from extras.models import Branch
from extras.models import StagedChange
from extras.signals import handle_deleted_object
from netbox.models import ChangeLoggedModel
from netbox.models import NetBoxModel
from netbox.models import PrimaryModel
from netbox.models.features import JobsMixin
from netbox.models.features import TagsMixin
from netbox.registry import registry
from netbox.staging import checkout
from utilities.data import shallow_compare_dict
from utilities.querysets import RestrictedQuerySet
from utilities.serialization import serialize_object

from .choices import IPFabricRawDataTypeChoices
from .choices import IPFabricSnapshotStatusModelChoices
from .choices import IPFabricSourceTypeChoices
from .choices import IPFabricSyncTypeChoices
from .choices import IPFabricTransformMapSourceModelChoices
from .utilities.ipfutils import IPFabric
from .utilities.ipfutils import IPFabricSyncRunner
from .utilities.ipfutils import render_jinja2
from .utilities.logging import SyncLogging


logger = logging.getLogger("ipfabric_netbox.models")


def apply_tags(object, tags):
    def _apply(object):
        for tag in tags:
            if hasattr(object, "tags"):
                object.tags.add(tag)
        object.save()

    _apply(object)


IPFabricSupportedSyncModels = Q(
    Q(app_label="dcim", model="site")
    | Q(app_label="dcim", model="manufacturer")
    | Q(app_label="dcim", model="platform")
    | Q(app_label="dcim", model="devicerole")
    | Q(app_label="dcim", model="devicetype")
    | Q(app_label="dcim", model="device")
    | Q(app_label="dcim", model="virtualchassis")
    | Q(app_label="dcim", model="interface")
    | Q(app_label="ipam", model="vlan")
    | Q(app_label="ipam", model="vrf")
    | Q(app_label="ipam", model="prefix")
    | Q(app_label="ipam", model="ipaddress")
    | Q(app_label="contenttypes", model="contenttype")
    | Q(app_label="tenancy", model="tenant")
    # TODO: Inventory Item broken util https://github.com/netbox-community/netbox/issues/13422 is resolved
    # | Q(app_label="dcim", model="inventoryitem")
)


IPFabricRelationshipFieldSourceModels = Q(
    Q(app_label="dcim")
    | Q(app_label="ipam")
    | Q(app_label="tenancy")
    | Q(app_label="contenttypes", model="contenttype")
)


class IPFabricTransformMap(NetBoxModel):
    name = models.CharField(max_length=100, unique=True)
    source_model = models.CharField(
        max_length=50, choices=IPFabricTransformMapSourceModelChoices
    )
    target_model = models.ForeignKey(
        to=ContentType,
        related_name="+",
        verbose_name="Target Model",
        limit_choices_to=IPFabricSupportedSyncModels,
        help_text=_("The object(s) to which transform map target applies."),
        on_delete=models.PROTECT,
        blank=False,
        null=False,
    )
    status = models.CharField(
        max_length=50,
    )

    class Meta:
        verbose_name = "IP Fabric Transform Map"
        verbose_name_plural = "IP Fabric Transform Maps"

    def __str__(self):
        if self.source_model and self.target_model:
            return f"{self.source_model} - {self.target_model}"
        else:
            return "Transform Map"

    def get_absolute_url(self):
        return reverse("plugins:ipfabric_netbox:ipfabrictransformmap", args=[self.pk])

    @property
    def docs_url(self):
        # TODO: Add docs url
        return ""

    def get_models(self):
        _context = dict()

        for app, model_names in registry["model_features"]["custom_fields"].items():
            _context.setdefault(app, {})
            for model_name in model_names:
                model = apps.get_registered_model(app, model_name)
                _context[app][model.__name__] = model
        _context["contenttypes"] = {}
        _context["contenttypes"]["ContentType"] = ContentType
        return _context

    def build_relationships(self, uuid, source_data):
        relationship_maps = self.relationship_maps.all()
        rel_dict = {}
        rel_dict_coalesce = {}

        for field in relationship_maps:
            if field.template:
                context = {
                    "object": source_data,
                }
                context.update(self.get_models())
                text = render_jinja2(field.template, context).strip()
                if text:
                    try:
                        pk = int(text)
                    except ValueError:
                        pk = text

                    if isinstance(pk, int):
                        related_object = field.source_model.model_class().objects.get(
                            pk=pk
                        )
                    else:
                        related_object = ast.literal_eval(pk)

                    if not field.coalesce:
                        rel_dict[field.target_field] = related_object
                    else:
                        rel_dict_coalesce[field.target_field] = related_object
            elif uuid and self.relationship_store.get(uuid):
                object = self.relationship_store[uuid].get(
                    field.source_model.model_class()
                )
                if object:
                    if not field.coalesce:
                        rel_dict[field.target_field] = object
                    else:
                        rel_dict_coalesce[field.target_field] = object

        return rel_dict, rel_dict_coalesce

    def update_or_create_instance(
        self, data, tags=[], uuid=None, relationship_store={}, logger=None
    ):
        self.relationship_store = relationship_store
        new_data = deepcopy(data)
        relationship, coalesce_relationship = self.build_relationships(
            uuid=uuid, source_data=data
        )

        if relationship:
            new_data["relationship"] = relationship
        if coalesce_relationship:
            new_data["relationship_coalesce"] = coalesce_relationship
        context = self.render(new_data)
        try:
            instance, _ = self.target_model.model_class().objects.update_or_create(
                **context
            )
            if instance:
                apply_tags(instance, tags)
        except Exception as e:
            error_message = f"""Failed to create instance:<br/>
            message: `{e}`<br/>
            raw data: `{data}`<br/>
            context: `{context}`<br/>
            """
            logger.log_failure(error_message, obj=self)
            logger.log_failure(
                "Ensure that all transform map fields are present.", obj=self
            )
            raise SyncError("Unable to update_or_create_instance.")

        return instance

    def get_coalesce_fields(self, source_data):
        data = self.render(source_data)
        del data["defaults"]
        return data

    def render(self, source_data):
        data = {"defaults": {}}
        for field in self.field_maps.all():
            if field.template:
                context = {
                    "object": source_data,
                    field.source_field: source_data[field.source_field],
                }
                context.update(self.get_models())
                text = render_jinja2(field.template, context).strip()
            else:
                text = source_data[field.source_field]

            if text is not None:
                if isinstance(text, str):
                    if text.lower() in ["true"]:
                        text = True
                    elif text.lower() in ["false"]:
                        text = False
                    elif text.lower() in ["none"]:
                        text = None

                    if text:
                        target_field = getattr(
                            self.target_model.model_class(), field.target_field
                        )
                        target_field_type = target_field.field.get_internal_type()
                        if "integer" in target_field_type.lower():
                            text = int(text)

            if not field.coalesce:
                data["defaults"][field.target_field] = text
            else:
                data[field.target_field] = text

        if relationship := source_data.get("relationship"):
            data["defaults"].update(relationship)

        if relationship_coalesce := source_data.get("relationship_coalesce"):
            data.update(relationship_coalesce)

        if self.status:
            data["defaults"]["status"] = self.status

        return data


class IPFabricRelationshipField(models.Model):
    transform_map = models.ForeignKey(
        to=IPFabricTransformMap,
        on_delete=models.CASCADE,
        related_name="relationship_maps",
        editable=True,
    )
    source_model = models.ForeignKey(
        ContentType,
        related_name="ipfabric_transform_fields",
        limit_choices_to=IPFabricRelationshipFieldSourceModels,
        verbose_name="Source Model",
        on_delete=models.PROTECT,
        blank=False,
        null=False,
    )
    target_field = models.CharField(max_length=100)
    coalesce = models.BooleanField(default=False)

ipfabric_netbox/templates/ipfabric_netbox/inc/diff.html
<div class="modal-header">
    <h5 class="modal-title">Change Diff {{ change }}</h5>
    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
</div>
<div class="modal-body">
    <div class="row mb-3">
        <div class="col-6">
            <div class="card">
                <h5 class="card-header">Pre-Change Data</h5>
                <div class="card-body">
                    {% if prechange_data %}
                    <pre class="change-data">{% for k, v in prechange_data.items %}{% spaceless %}
                        <span{% if k in diff_removed %} class="removed"{% endif %}>{{ k }}: {{ v|json }}</span>
                    {% endspaceless %}{% endfor %}
                </pre>
                    {% else %}
                    <span class="text-muted">None</span>
                    {% endif %}
                </div>
            </div>
        </div>
        <div class="col-6">
            <div class="card">
                <h5 class="card-header">Post-Change Data</h5>
                <div class="card-body">
                    {% if postchange_data %}
                    <pre class="change-data">{% for k, v in postchange_data.items %}{% spaceless %}
                        <span{% if k in diff_removed %} class="added"{% endif %}>{{ k }}: {{ v|json }}</span>
                        {% endspaceless %}{% endfor %}{% endif %}
                </div>
            </div>
      </div>
    </div>
    <div class="row">
        <div class="col">
            <div class="card">
                <div class="card-header">
                    <h5 class="d-inline">Difference</h5>
                    <!-- <div class="btn-group btn-group-sm float-end noprint">
                            <a {% if prev_change %}href="{% url 'extras:objectchange' pk=prev_change.pk %}"{% else %}disabled{% endif %} class="btn btn-outline-secondary">
                                <i class="mdi mdi-chevron-left" aria-hidden="true"></i> Previous
                            </a>
                            <a {% if next_change %}href="{% url 'extras:objectchange' pk=next_change.pk %}"{% else %}disabled{% endif %} class="btn btn-outline-secondary">
                                Next <i class="mdi mdi-chevron-right" aria-hidden="true"></i>
                            </a>
                        </div> -->
                </div>
                <div class="card-body">
                    {% if diff_added == diff_removed %}
                    <span class="text-muted" style="margin-left: 10px;">
                        {% if object.action == 'create' %}
                        Object Created
                        {% elif object.action == 'delete' %}
                        Object Deleted
                        {% else %}
                        No Changes
                        {% endif %}
                    </span>
                    {% else %}
                    <pre class="change-diff change-removed">{{ diff_removed|json }}</pre>
                    <pre class="change-diff change-added">{{ diff_added|json }}</pre>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
</div>

<div class="modal-footer">
</div>
</div>

ipfabric_netbox/templates/ipfabric_netbox/inc/json.html
<div class="modal-header">
    <h5 class="modal-title">Raw Data {{ object.pk }}</h5>
    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
</div>
<div class="modal-body">
    <div class="row mb-3">
        <div class="col-12">
            <div class="card">
                <h5 class="card-header">JSON Output</h5>
                <div class="card-body">
                    <pre>{{ object.data | json }}</pre>
                </div>
            </div>
      </div>
    </div>
</div>

<div class="modal-footer">
</div>
</div>

ipfabric_netbox/templates/ipfabric_netbox/inc/logs_pending.html
{# Indicates that a job result is still pending; used for HTMX requests #}
<div class="spinner-border float-start me-1" id="spinner" role="status">
  <span class="visually-hidden">Loading...</span>
</div>
<h3>Logs pending...</h3>
<small class="text-muted">Last updated {% now "H:i:s" %}</small>

ipfabric_netbox/templates/ipfabric_netbox/inc/merge_form.html
{% load form_helpers %}

<form action="{{ form_url }}" method="post">
  {% csrf_token %}
  <div class="modal-header">
    <h5 class="modal-title">Confirm Merge</h5>
  </div>
  <div class="modal-body">
    <p>Are you sure you want to <strong class="text-danger">merge</strong> {{ object_type }} <strong>{{ object }}</strong>?</p>
    {% render_form form %}
  </div>
  <div class="modal-footer">
    {% if return_url %}
      <a href="{{ return_url }}" class="btn btn-outline-secondary">Cancel</a>
    {% else %}
      <button type="button" class="btn btn-outline-secondary" data-bs-dismiss="modal">Cancel</button>
    {% endif %}
    <button type="submit" class="btn btn-danger">Merge</button>
  </div>
</form>

ipfabric_netbox/templates/ipfabric_netbox/inc/site_topology_button.html
{% if object.custom_field_data.ipfabric_source %}
<div class="btn-group" role="group" aria-label="Button group with nested dropdown">
  <div class="btn-group" role="group">
    <button id="btnGroupDrop1" type="button" class="btn btn-sm btn-success dropdown-toggle" data-bs-toggle="dropdown"
      aria-expanded="false">
      IP Fabric Topology
    </button>
    <ul class="dropdown-menu" aria-labelledby="btnGroupDrop1">
      <li><a href="#"
          hx-get="{% url 'plugins:ipfabric_netbox:ipfabricsource_topology' pk=object.pk site=object.pk %}?snapshot=$last&source={{ object.custom_field_data.ipfabric_source }}"
          hx-target="#topology-modal-content" data-bs-toggle="modal" data-bs-target="#topology-modal"
          class="dropdown-item">
          Last Snapshot
        </a>
      </li>
      <li><a href="#"
          hx-get="{% url 'plugins:ipfabric_netbox:ipfabricsource_topology' pk=object.pk site=object.pk %}?snapshot=$prev&source={{ object.custom_field_data.ipfabric_source }}"
          hx-target="#topology-modal-content" data-bs-toggle="modal" data-bs-target="#topology-modal"
          class="dropdown-item">
          Previous Snapshot
        </a></li>
    </ul>
  </div>
</div>

<div class="modal fade" id="topology-modal" tabindex="-1" aria-hidden="true">
  <div class="modal-dialog modal-xl">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">{{ object.name }} Topology</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div id="topology-modal-content">
        <div class="modal-body">
          <div class="d-flex align-items-center">
            <strong role="status">Loading...</strong>
            <div class="spinner-border ms-auto" aria-hidden="true"></div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
{% endif %}

{% block javascript %}
<script>
  document.addEventListener('DOMContentLoaded', function () {
    var myModal = document.getElementById('topology-modal');
    var modalBody = document.getElementById('topology-modal-content');
    console.log(myModal);
    myModal.addEventListener('hidden.bs.modal', function () {
      // Clear modal content on close
      console.log("Modal close");
      modalBody.innerHTML = createLoadingContent();
    });
  });

  function createLoadingContent() {
    return `
      <div class="modal-body">
        <div class="d-flex align-items-center">
          <strong role="status">Loading...</strong>
          <div class="spinner-border ms-auto" aria-hidden="true"></div>
        </div>
      </div>
    `;
  }
</script>
{% endblock %}

ipfabric_netbox/templates/ipfabric_netbox/inc/site_topology_modal.html
{% load helpers %}

<div class="modal-body">
    <div class="d-flex flex-row m-2"">
    {% if svg %}
        <div class=" d-flex flex-row flex-grow-1 align-items-center">
            {{svg|safe}}
        </div>
        <div>
            <div class="position-absolute top-0 end-0 m-2 border rounded p-2">
                <ul class="list-unstyled">
                    <li><span>Fetched: {{ time|isodatetime }}</span></li>
                    <li>Snapshot Name: {{ snapshot.name }}</li>
                    <li>Snapshot ID: {{ snapshot.snapshot_id }}</li>
                    <li>Snapshot Date: {{ snapshot.end|isodatetime }}</li>
                </ul>
            </div>
        </div>
    {% else %}
        <div class="d-flex flex-row flex-grow-1 align-items-center">
            {{ error }}
        </div>
        {% if snapshot %}
        <div>
            <div class="border rounded p-2">
                <ul class="list-unstyled">
                    <li><span>Fetched: {{ time|isodatetime }}</span></li>
                    <li>Snapshot Name: {{ snapshot.name }}</li>
                    <li>Snapshot ID: {{ snapshot.snapshot_id }}</li>
                    <li>Snapshot Date: {{ snapshot.end|isodatetime }}</li>
                </ul>
            </div>
        </div>
        {% endif %}
    {% endif %}
</div>
</div>
{% if link %}
<div class="modal-footer">
    <a href="#" hx-get="{% url 'plugins:ipfabric_netbox:ipfabricsource_topology' pk=source.pk site=site.pk %}?snapshot={{ snapshot.snapshot_id }}"
        hx-target="#topology-modal-content" class="btn btn-success" hx-indicator=".my-indicator"><span
            class="spinner-border spinner-border-sm loader my-indicator" role="status" aria-hidden="true"></span>
        Refresh</a>
    <a href="{{ link }}" class="btn btn-primary" target="_blank">Open in IP Fabric</a>
</div>
{% endif %}

<style type="text/css">
    .my-indicator {
        display: none !important;
        ;
    }

    .htmx-request .my-indicator {
        display: inline-block !important;
    }

    .htmx-request.my-indicator {
        display: inline-block !important;
    }
</style>

ipfabric_netbox/templates/ipfabric_netbox/inc/snapshotdata.html
{% extends base_template %}
{% load helpers %}
{% load i18n %}

{% block content %}
    {% block table_controls %}
        {% include 'inc/table_controls_htmx.html' with table_modal=table_config %}
    {% endblock table_controls %}
    <form method="post">
        {% csrf_token %}
        <div class="card">
            <div class="card-body htmx-container table-responsive" id="object_list">
                {% include 'htmx/table.html' %}
            </div>
        </div>
        <div class="noprint bulk-buttons">
            {% block bulk_controls %}
                <div class="bulk-button-group">
                    <div class="btn-group" role="group">
                        {# Bulk edit buttons #}
                        {% block bulk_edit_controls %}
                            {% with bulk_edit_view=child_model|validated_viewname:"bulk_edit" %}
                                {% if 'bulk_edit' in actions and bulk_edit_view %}
                                    <button type="submit" name="_edit"
                                            formaction="{% url bulk_edit_view %}?return_url={{ return_url }}"
                                            class="btn btn-warning btn-sm">
                                        <i class="mdi mdi-pencil" aria-hidden="true"></i> {% trans "Edit Selected" %}
                                    </button>
                                {% endif %}
                            {% endwith %}
                        {% endblock bulk_edit_controls %}
                    </div>
                    <div class="btn-group" role="group">
                        {# Bulk delete buttons #}
                        {% block bulk_delete_controls %}
                            {% with bulk_delete_view=child_model|validated_viewname:"bulk_delete" %}
                                {% if 'bulk_delete' in actions and bulk_delete_view %}
                                    <button type="submit"
                                            formaction="{% url bulk_delete_view %}?return_url={{ return_url }}"
                                            class="btn btn-danger btn-sm">
                                        <i class="mdi mdi-trash-can-outline" aria-hidden="true"></i> {% trans "Delete Selected" %}
                                    </button>
                                {% endif %}
                            {% endwith %}
                        {% endblock bulk_delete_controls %}
                    </div>
                </div>
                <div class="bulk-button-group">
                    {# Other bulk action buttons #}
                    {% block bulk_extra_controls %}{% endblock %}
                </div>
            {% endblock bulk_controls %}
        </div>
    </form>
{% endblock content %}

{% block modals %}
    {{ block.super }}
    {% table_config_form table %}
{% endblock modals %}

ipfabric_netbox/templates/ipfabric_netbox/inc/sync_delete.html
{% load form_helpers %}

<form action="{{ form_url }}" method="post">
  {% csrf_token %}
  <div class="modal-header">
    <h5 class="modal-title">Sorry!</h5>
  </div>
  <div class="modal-body">
    <p>Sorry, due to an outstanding issue with NetBox Core we are unable to delete an ingestion. <a href="https://github.com/netbox-community/netbox/issues/13640" target="_blank">Issue Number 13422</a></p>
    {% render_form form %}
  </div>
  <div class="modal-footer">
    {% if return_url %}
      <a href="{{ return_url }}" class="btn btn-outline-secondary">Cancel</a>
    {% else %}
      <button type="button" class="btn btn-outline-secondary" data-bs-dismiss="modal">Cancel</button>
    {% endif %}
  </div>
</form>

ipfabric_netbox/templates/ipfabric_netbox/inc/transform_map_field_map.html
{% extends 'generic/object_children.html' %}

{% block extra_controls %}
{% if perms.ipfabric_netbox.add_ipfabrictransformfield %}
    <a href="{% url 'plugins:ipfabric_netbox:ipfabrictransformfield_add' %}?transform_map={{ object.pk }}&return_url={% url 'plugins:ipfabric_netbox:ipfabrictransformmap_fields' pk=object.pk %}"
        class="btn btn-primary">
        <i class="mdi mdi-plus-thick" aria-hidden="true"></i> Field Map
    </a>
{% endif %}
{{ block.super }}
{% endblock extra_controls %}

ipfabric_netbox/templates/ipfabric_netbox/inc/transform_map_relationship_map.html
{% extends 'generic/object_children.html' %}

{% block extra_controls %}
{% if perms.ipfabric_netbox.add_ipfabricrelationshipfield %}
<a href="{% url 'plugins:ipfabric_netbox:ipfabricrelationshipfield_add' %}?transform_map={{ object.pk }}&return_url={% url 'plugins:ipfabric_netbox:ipfabrictransformmap_relationships' pk=object.pk %}"
    class="btn btn-primary">
    <i class="mdi mdi-plus-thick" aria-hidden="true"></i> Relationship Map
</a>
{% endif %}
{{ block.super }}
{% endblock extra_controls %}