ipfabric_netbox/urls.py
from django.urls import include
from django.urls import path
from utilities.urls import get_model_urls

from . import views

urlpatterns = (
    # Source
    path("source/", views.IPFabricSourceListView.as_view(), name="ipfabricsource_list"),
    path(
        "source/add/", views.IPFabricSourceEditView.as_view(), name="ipfabricsource_add"
    ),
    path(
        "source/delete/",
        views.IPFabricSourceBulkDeleteView.as_view(),
        name="ipfabricsource_bulk_delete",
    ),
    path(
        "source/<int:pk>/delete/",
        views.IPFabricSourceDeleteView.as_view(),
        name="ipfabricsource_delete",
    ),
    path(
        "source/<int:pk>/", include(get_model_urls("ipfabric_netbox", "ipfabricsource"))
    ),
    path(
        "source/delete/",
        views.IPFabricSyncBulkDeleteView.as_view(),
        name="ipfabricsync_bulk_delete",
    ),
    # Snapshot
    path(
        "snapshot/",
        views.IPFabricSnapshotListView.as_view(),
        name="ipfabricsnapshot_list",
    ),
    path(
        "snapshot/delete/",
        views.IPFabricSnapshotBulkDeleteView.as_view(),
        name="ipfabricsnapshot_bulk_delete",
    ),
    path(
        "snapshot/<int:pk>/",
        include(get_model_urls("ipfabric_netbox", "ipfabricsnapshot")),
    ),
    path(
        "snapshot/<int:pk>/delete/",
        views.IPFabricSnapshotDeleteView.as_view(),
        name="ipfabricsnapshot_delete",
    ),
    path(
        "data/<int:pk>/delete",
        views.IPFabricSnapshotDataDeleteView.as_view(),
        name="ipfabricdata_delete",
    ),
    path("data/<int:pk>/", include(get_model_urls("ipfabric_netbox", "ipfabricdata"))),
    path(
        "data/delete",
        views.IPFabricSnapshotDataBulkDeleteView.as_view(),
        name="ipfabricdata_bulk_delete",
    ),
    # Sync
    path("sync/", views.IPFabricSyncListView.as_view(), name="ipfabricsync_list"),
    path("sync/add/", views.IPFabricSyncEditView.as_view(), name="ipfabricsync_add"),
    path("sync/<int:pk>/", include(get_model_urls("ipfabric_netbox", "ipfabricsync"))),
    # Branch
    path("branch/", views.IPFabricBranchListView.as_view(), name="ipfabricbranch_list"),
    path(
        "branch/<int:pk>/", include(get_model_urls("ipfabric_netbox", "ipfabricbranch"))
    ),
    # Transform Map
    path(
        "transform-map/",
        views.IPFabricTransformMapListView.as_view(),
        name="ipfabrictransformmap_list",
    ),
    path(
        "transform-map/restore/",
        views.IPFabricTransformMapRestoreView.as_view(),
        name="ipfabrictransformmap_restore",
    ),
    path(
        "transform-map/add",
        views.IPFabricTransformMapEditView.as_view(),
        name="ipfabrictransformmap_add",
    ),
    path(
        "transform-map/delete/",
        views.IPFabricTransformMapBulkDeleteView.as_view(),
        name="ipfabrictransformmap_bulk_delete",
    ),
    path(
        "transform-map/<int:pk>/",
        include(get_model_urls("ipfabric_netbox", "ipfabrictransformmap")),
    ),
    path(
        "transform-map/<int:pk>/delete/",
        views.IPFabricTransformMapDeleteView.as_view(),
        name="ipfabrictransformmap_delete",
    ),
    # Transform field
    path(
        "transform-field/",
        views.IPFabricTransformFieldListView.as_view(),
        name="ipfabrictransformfield_list",
    ),
    path(
        "transform-field/add/",
        views.IPFabricTransformFieldEditView.as_view(),
        name="ipfabrictransformfield_add",
    ),
    path(
        "transform-field/<int:pk>/",
        include(get_model_urls("ipfabric_netbox", "ipfabrictransformfield")),
    ),
    path(
        "transform-field/<int:pk>/delete/",
        views.IPFabricTransformFieldDeleteView.as_view(),
        name="ipfabrictransformfield_delete",
    ),
    # Relationship Field
    path(
        "relationship-field/",
        views.IPFabricRelationshipFieldListView.as_view(),
        name="ipfabricrelationshipfield_list",
    ),
    path(
        "relationship-field/add/",
        views.IPFabricRelationshipFieldEditView.as_view(),
        name="ipfabricrelationshipfield_add",
    ),
    path(
        "relationship-field/<int:pk>/",
        include(get_model_urls("ipfabric_netbox", "ipfabricrelationshipfield")),
    ),
    path(
        "relationship-field/<int:pk>/delete/",
        views.IPFabricRelationshipFieldDeleteView.as_view(),
        name="ipfabricrelationshipfield_delete",
    ),
)

ipfabric_netbox/models.py
import ast
import json
import logging
import traceback
from copy import deepcopy

import httpx
from core.choices import DataSourceStatusChoices
from core.exceptions import SyncError
from core.models import Job
from core.signals import pre_sync
from dcim.models import VirtualChassis
from dcim.signals import assign_virtualchassis_master
from django.apps import apps
from django.conf import settings
from django.contrib.contenttypes.models import ContentType
from django.core.cache import cache
from django.core.validators import MinValueValidator
from django.db import models
from django.db import transaction
from django.db.models import Q
from django.db.models import signals
from django.urls import reverse
from django.utils import timezone
from django.utils.module_loading import import_string
from django.utils.translation import gettext as _
from extras.models import Branch
from extras.models import StagedChange
from extras.signals import handle_deleted_object
from netbox.models import ChangeLoggedModel
from netbox.models import NetBoxModel
from netbox.models import PrimaryModel
from netbox.models.features import JobsMixin
from netbox.models.features import TagsMixin
from netbox.registry import registry
from netbox.staging import checkout
from utilities.data import shallow_compare_dict
from utilities.querysets import RestrictedQuerySet
from utilities.serialization import serialize_object

from .choices import IPFabricRawDataTypeChoices
from .choices import IPFabricSnapshotStatusModelChoices
from .choices import IPFabricSourceTypeChoices
from .choices import IPFabricSyncTypeChoices
from .choices import IPFabricTransformMapSourceModelChoices
from .utilities.ipfutils import IPFabric
from .utilities.ipfutils import IPFabricSyncRunner
from .utilities.ipfutils import render_jinja2
from .utilities.logging import SyncLogging


logger = logging.getLogger("ipfabric_netbox.models")


def apply_tags(object, tags):
    def _apply(object):
        for tag in tags:
            if hasattr(object, "tags"):
                object.tags.add(tag)
        object.save()

    _apply(object)


IPFabricSupportedSyncModels = Q(
    Q(app_label="dcim", model="site")
    | Q(app_label="dcim", model="manufacturer")
    | Q(app_label="dcim", model="platform")
    | Q(app_label="dcim", model="devicerole")
    | Q(app_label="dcim", model="devicetype")
    | Q(app_label="dcim", model="device")
    | Q(app_label="dcim", model="virtualchassis")
    | Q(app_label="dcim", model="interface")
    | Q(app_label="ipam", model="vlan")
    | Q(app_label="ipam", model="vrf")
    | Q(app_label="ipam", model="prefix")
    | Q(app_label="ipam", model="ipaddress")
    | Q(app_label="contenttypes", model="contenttype")
    | Q(app_label="tenancy", model="tenant")
    # TODO: Inventory Item broken util https://github.com/netbox-community/netbox/issues/13422 is resolved
    # | Q(app_label="dcim", model="inventoryitem")
)


IPFabricRelationshipFieldSourceModels = Q(
    Q(app_label="dcim")
    | Q(app_label="ipam")
    | Q(app_label="tenancy")
    | Q(app_label="contenttypes", model="contenttype")
)


class IPFabricTransformMap(NetBoxModel):
    name = models.CharField(max_length=100, unique=True)
    source_model = models.CharField(
        max_length=50, choices=IPFabricTransformMapSourceModelChoices
    )
    target_model = models.ForeignKey(
        to=ContentType,
        related_name="+",
        verbose_name="Target Model",
        limit_choices_to=IPFabricSupportedSyncModels,
        help_text=_("The object(s) to which transform map target applies."),
        on_delete=models.PROTECT,
        blank=False,
        null=False,
    )
    status = models.CharField(
        max_length=50,
    )

    class Meta:
        verbose_name = "IP Fabric Transform Map"
        verbose_name_plural = "IP Fabric Transform Maps"

    def __str__(self):
        if self.source_model and self.target_model:
            return f"{self.source_model} - {self.target_model}"
        else:
            return "Transform Map"

    def get_absolute_url(self):
        return reverse("plugins:ipfabric_netbox:ipfabrictransformmap", args=[self.pk])

    @property
    def docs_url(self):
        # TODO: Add docs url
        return ""

    def get_models(self):
        _context = dict()

        for app, model_names in registry["model_features"]["custom_fields"].items():
            _context.setdefault(app, {})
            for model_name in model_names:
                model = apps.get_registered_model(app, model_name)
                _context[app][model.__name__] = model
        _context["contenttypes"] = {}
        _context["contenttypes"]["ContentType"] = ContentType
        return _context

    def build_relationships(self, uuid, source_data):
        relationship_maps = self.relationship_maps.all()
        rel_dict = {}
        rel_dict_coalesce = {}

        for field in relationship_maps:
            if field.template:
                context = {
                    "object": source_data,
                }
                context.update(self.get_models())
                text = render_jinja2(field.template, context).strip()
                if text:
                    try:
                        pk = int(text)
                    except ValueError:
                        pk = text

                    if isinstance(pk, int):
                        related_object = field.source_model.model_class().objects.get(
                            pk=pk
                        )
                    else:
                        related_object = ast.literal_eval(pk)

                    if not field.coalesce:
                        rel_dict[field.target_field] = related_object
                    else:
                        rel_dict_coalesce[field.target_field] = related_object
            elif uuid and self.relationship_store.get(uuid):
                object = self.relationship_store[uuid].get(
                    field.source_model.model_class()
                )
                if object:
                    if not field.coalesce:
                        rel_dict[field.target_field] = object
                    else:
                        rel_dict_coalesce[field.target_field] = object

        return rel_dict, rel_dict_coalesce

    def update_or_create_instance(
        self, data, tags=[], uuid=None, relationship_store={}, logger=None
    ):
        self.relationship_store = relationship_store
        new_data = deepcopy(data)
        relationship, coalesce_relationship = self.build_relationships(
            uuid=uuid, source_data=data
        )

        if relationship:
            new_data["relationship"] = relationship
        if coalesce_relationship:
            new_data["relationship_coalesce"] = coalesce_relationship
        context = self.render(new_data)
        try:
            instance, _ = self.target_model.model_class().objects.update_or_create(
                **context
            )
            if instance:
                apply_tags(instance, tags)
        except Exception as e:
            error_message = f"""Failed to create instance:<br/>
            message: `{e}`<br/>
            raw data: `{data}`<br/>
            context: `{context}`<br/>
            """
            logger.log_failure(error_message, obj=self)
            logger.log_failure(
                "Ensure that all transform map fields are present.", obj=self
            )
            raise SyncError("Unable to update_or_create_instance.")

        return instance

    def get_coalesce_fields(self, source_data):
        data = self.render(source_data)
        del data["defaults"]
        return data

    def render(self, source_data):
        data = {"defaults": {}}
        for field in self.field_maps.all():
            if field.template:
                context = {
                    "object": source_data,
                    field.source_field: source_data[field.source_field],
                }
                context.update(self.get_models())
                text = render_jinja2(field.template, context).strip()
            else:
                text = source_data[field.source_field]

            if text is not None:
                if isinstance(text, str):
                    if text.lower() in ["true"]:
                        text = True
                    elif text.lower() in ["false"]:
                        text = False
                    elif text.lower() in ["none"]:
                        text = None

                    if text:
                        target_field = getattr(
                            self.target_model.model_class(), field.target_field
                        )
                        target_field_type = target_field.field.get_internal_type()
                        if "integer" in target_field_type.lower():
                            text = int(text)

            if not field.coalesce:
                data["defaults"][field.target_field] = text
            else:
                data[field.target_field] = text

        if relationship := source_data.get("relationship"):
            data["defaults"].update(relationship)

        if relationship_coalesce := source_data.get("relationship_coalesce"):
            data.update(relationship_coalesce)

        if self.status:
            data["defaults"]["status"] = self.status

        return data


class IPFabricRelationshipField(models.Model):
    transform_map = models.ForeignKey(
        to=IPFabricTransformMap,
        on_delete=models.CASCADE,
        related_name="relationship_maps",
        editable=True,
    )
    source_model = models.ForeignKey(
        ContentType,
        related_name="ipfabric_transform_fields",
        limit_choices_to=IPFabricRelationshipFieldSourceModels,
        verbose_name="Source Model",
        on_delete=models.PROTECT,
        blank=False,
        null=False,
    )
    target_field = models.CharField(max_length=100)
    coalesce = models.BooleanField(default=False)

ipfabric_netbox/templates/ipfabric_netbox/ipfabric_table.html
{% extends 'generic/object.html' %}
{% load static %}
{% load form_helpers %}
{% load i18n %}

{% block content %}
{{ object.custom_field }}

{% if source %}
  {% if not object.serial %}
  <div class="row px-3">
    <div class="card">
      <div class="card-body">
        Device does not have a serial number configured. The serial number is used to match devices between NetBox and IP Fabric.
      </div>
    </div>
  </div>
  {% elif source.type == "remote" %}
  <div class="row px-3">
    <div class="card">
      <div class="card-body">
        Device has a remote IP Fabric Source configured and cannot directly query IP Fabric.
      </div>
    </div>
  {% else %}
  <div class="row px-3">
    <div class="col col-12 py-3 mx-auto">
      <form action="{% url 'dcim:device' pk=object.pk %}ipfabric" method="get" class="form form-horizontal">
        {% render_form form %}
        <div class="text-end">
          <button type="submit" class="btn btn-primary">
            <span class="mdi mdi-magnify" aria-hidden="true"></span> Fetch
          </button>
        </div>
      </form>
    </div>
  </div>
  <div class="row px-3">
    <div class="card">
      <div class="card-body htmx-container table-responsive" id="object_list">
        {% include 'htmx/table.html' %}
      </div>
    </div>
  </div>
  {% endif %}
{% else %}
  <div class="row px-3">
    <div class="card">
      <div class="card-body">
        Device does not have a IP Fabric source configured in the custom fields. The source is used to match devices between NetBox and IP Fabric instance.
      </div>
    </div>
  </div>
{% endif %}
{% endblock %}

ipfabric_netbox/templates/ipfabric_netbox/ipfabricbranch.html
{% extends 'generic/object.html' %}
{% load buttons %}
{% load custom_links %}
{% load helpers %}
{% load perms %}
{% load plugins %}
{% load tabs %}

{% block title %}{{ object }}{% endblock %}

{% block control-buttons %}
{# Clone/Edit/Delete Buttons #}
<div class="controls">
  <div class="control-group">
    {% custom_links object %}
  </div>
{% if perms.core.sync_datasource %}
{% if object.sync.ready_for_sync %}
  <a href="#"
  hx-get="{% url 'plugins:ipfabric_netbox:ipfabricbranch_merge' pk=object.pk %}"
  hx-target="#htmx-modal-content"
  class="btn btn-success"
  data-bs-toggle="modal"
  data-bs-target="#htmx-modal" disabled
  >
  <span class="mdi mdi-sync" aria-hidden="true"></span>&nbsp;Merge
  </a>
{% else %}
<span class="inline-block" tabindex="0" data-bs-toggle="tooltip" data-bs-delay="100" data-bs-placement="bottom">
  <button class="btn btn-success" disabled>
    <i class="mdi mdi-sync" aria-hidden="true"></i> Merge
  </button>
</span>
{% endif %}
{% endif %}
</div>
{% endblock control-buttons %}


{% block content %}
<div class="row mb-3">
  <div class="col col-md-6">
    <div class="card">
      <h5 class="card-header">Branch Information</h5>
      <div class="card-body">
        <table class="table table-hover attr-table">
          <tr>
            <th scope="row">Name</th>
            <td>{{ object.name }}</td>
          </tr>
          <tr>
            <th scope="row">Description</th>
            <td>{{ object.description|placeholder }}</td>
          </tr>
          <tr>
            <th scope="row">Sync Object</th>
            <td><a href="{% url 'plugins:ipfabric_netbox:ipfabricsync' pk=object.sync.pk %}">{{ object.sync.name}}</a>
            </td>
          </tr>
          <tr>
            <th scope="row">Job Object</th>
            <td><a href="{% url 'core:job' pk=object.job.pk %}">{{ object.job }}</a></td>
          </tr>
          <tr>
            <th scope="row">Sync Status</th>
              <td><div id="sync_status" hx-swap-oob="true">{% include 'ipfabric_netbox/partials/branch_status.html' with object=object %}</div></td>
              <!-- <td >{% badge object.sync.get_status_display bg_color=object.sync.get_status_color %}</td> -->
            </div>
          </tr>
          <tr>
            <th scope="row">Snapshot</th>
            <td><a
                href="{% url 'plugins:ipfabric_netbox:ipfabricsnapshot' pk=object.sync.snapshot_data.pk %}">{{object.sync.snapshot_data.name }}</a></td>
          </tr>
          <tr>
            <th scope="row">Source</th>
            <td><a
                href="{% url 'plugins:ipfabric_netbox:ipfabricsource' pk=object.sync.snapshot_data.source.pk %}">{{object.sync.snapshot_data.source.name }}</a></td>
          </tr>
        </table>
      </div>
    </div>
    {% plugin_left_page object %}
  </div>
  <div class="col col-md-6">
    <div class="card">
      <h5 class="card-header">Statistics</h5>
      <div class="card-body">
        <table class="table table-hover attr-table">
          <tr>
            <th scope="row">Created</th>
            <td>
              {% if object.num_created %}
              {{ object.num_created }}
              {% else %}
              {{ ''|placeholder }}
              {% endif %}
            </td>
          </tr>
          <tr>
            <th scope="row">Updated</th>
            <td>
              {% if object.num_updated %}
              {{ object.num_updated }}
              {% else %}
              {{ ''|placeholder }}
              {% endif %}
            </td>
          </tr>
          <tr>
            <th scope="row">Deleted</th>
            <td>
              {% if object.num_deleted %}
              {{ object.num_deleted }}
              {% else %}
              {{ ''|placeholder }}
              {% endif %}
            </td>
          </tr>
        </table>
      </div>
    </div>
    <div id="sync_progress">
      {% include 'ipfabric_netbox/partials/branch_progress.html' %}
    </div>
    <!-- {% include 'inc/panels/related_objects.html' %} -->
    {% include 'inc/panels/custom_fields.html' %}
    {% plugin_right_page object %}
  </div>
</div>
<div class="row mb-3">
  <div class="col col-md-12" {% if not object.job.completed %} hx-get="{% url 'plugins:ipfabric_netbox:ipfabricbranch_logs' pk=object.pk %}?type=info"
    hx-trigger="every 5s" hx-target="#sync_logs" hx-select="#sync_logs" hx-select-oob="#sync_status:innerHTML"
    hx-swap="innerHTML" {% endif %}>
    <div id="sync_logs">{% include 'ipfabric_netbox/partials/job_logs.html' with job=object.job %}</div>
  </div>
{% endblock content %}

  {% block modals %}
  {% include 'inc/htmx_modal.html' with size='lg' %}
  {% endblock modals %}

ipfabric_netbox/templates/ipfabric_netbox/ipfabricsnapshot.html
{% extends 'generic/object.html' %}
{% load buttons %}
{% load helpers %}
{% load perms %}

{% block controls %}
  <div class="controls">
    <div class="control-group">
      {% if request.user|can_delete:object %}
        {% delete_button object %}
      {% endif %}
    </div>
  </div>
{% endblock controls %}

{% block content %}
  <div class="row mb-3">
    <div class="col col-md-6">
      <div class="card">
        <h5 class="card-header">Snapshot Information</h5>
        <div class="card-body">
          <table class="table table-hover attr-table">
            <tr>
              <th scope="row">Name</th>
              <td>{{ object.name|placeholder }}</td>
            </tr>
            <tr>
              <th scope="row">Snapshot ID</th>
              <td>{{ object.snapshot_id|placeholder }}</td>
            </tr>
            <tr>
                <th scope="row">Source</th>
                <td>
                    <a href="{% url 'plugins:ipfabric_netbox:ipfabricsource' pk=object.source.pk %}">{{ object.source }}</a>
                </td>
              </tr>
            <tr>
              <th scope="row">Last Updated</th>
              <td>{{ object.last_updated|placeholder }}</td>
            </tr>
          </table>
        </div>
      </div>
    </div>
    <div class="col col-md-6">
        <div class="card">
            <h5 class="card-header">Statistics</h5>
            <div class="card-body">
              <table class="table table-hover attr-table">
                <tr>
                    <th scope="row">Version</th>
                    <td>{{ object.data.version|placeholder }}</td>
                </tr>
                <tr>
                    <th scope="row">Status</th>
                    <td>{% badge object.get_status_display bg_color=object.get_status_color %}</td>
                </tr>
                <tr>
                    <th scope="row">Site Count</th>
                    <td>{{ object.data.sites|length|placeholder }}</td>
                </tr>
                <tr>
                    <th scope="row">Sites</th>
                    <td>
                        {% if object.data.sites %}
                            {% for site in object.data.sites %}
                                <span class="badge bg-info mt-1">
                                    {{ site }}
                                </span>
                            {% endfor %}
                        {% else %}
                            {{ ''|placeholder }}
                        {% endif %}
                    </td>
                </tr>
                <tr>
                    <th scope="row">Device Count</th>
                    <td>{{ object.data.total_dev_count|placeholder }}</td>
                </tr>
                <tr>
                    <th scope="row">Interface Count</th>
                    <td>{{ object.data.interface_count|placeholder }}</td>
                </tr>
                <tr>
                    <th scope="row">Note</th>
                    <td>
                        <pre>{{ object.data.note|placeholder }}</pre>
                    </td>
                </tr>
              </table>
            </div>
          </div>
    </div>
  </div>
  <div class="row">
    <div class="col col-12">
      <div class="card">
        <h5 class="card-header">Data</h5>
        <div class="card-body">
            <pre class="block">{{ object.data | json }}</pre>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

ipfabric_netbox/templates/ipfabric_netbox/ipfabricsource.html
{% extends 'generic/object.html' %}
{% load static %}
{% load helpers %}
{% load plugins %}
{% load render_table from django_tables2 %}
{% load perms %}

{% block extra_controls %}
{% if perms.ipfabric_netbox.sync_source %}
{% if object.ready_for_sync and object.type == 'local' %}
<form action="{% url 'plugins:ipfabric_netbox:ipfabricsource_sync' pk=object.pk %}" method="post">
  {% csrf_token %}
  <button type="submit" class="btn btn-primary">
    <i class="mdi mdi-sync" aria-hidden="true"></i> Sync
  </button>
</form>
{% else %}
<span class="inline-block" tabindex="0" data-bs-toggle="tooltip" data-bs-delay="100" data-bs-placement="bottom">
  <button class="btn btn-primary" disabled>
    <i class="mdi mdi-sync" aria-hidden="true"></i> Sync
  </button>
</span>
{% endif %}
{% endif %}
{% endblock %}

{% block content %}
<div class="row mb-3">
  <div class="col col-md-6">
    <div class="card">
      <h5 class="card-header">Data Source</h5>
      <div class="card-body">
        <table class="table table-hover attr-table">
          <tr>
            <th scope="row">Name</th>
            <td>{{ object.name }}</td>
          </tr>
          <tr>
            <th scope="row">Type</th>
            <td>{{ object.get_type_display }}</td>
          </tr>
          <tr>
            <th scope="row">Status</th>
            <td>{% badge object.get_status_display bg_color=object.get_status_color %}</td>
          </tr>
          <tr>
            <th scope="row">Last synced</th>
            <td>{{ object.last_synced|placeholder }}</td>
          </tr>
          <tr>
            <th scope="row">Description</th>
            <td>{{ object.description|placeholder }}</td>
          </tr>
          <tr>
            <th scope="row">URL</th>
            <td>
              <a href="{{ object.url }}">{{ object.url }}</a>
            </td>
          </tr>
        </table>
      </div>
    </div>
    {% include 'inc/panels/tags.html' %}
    {% include 'inc/panels/comments.html' %}
    {% plugin_left_page object %}
  </div>
  <div class="col col-md-6">
    <div class="card">
      <h5 class="card-header">Parameters</h5>
      <div class="card-body">
        <table class="table table-hover attr-table">
          {% for name, value in object.parameters.items %}
          <tr>
            <th scope="row">{{ name | capfirst}}</th>
            {% if name == "auth" and object.parameters|get_key:name %}
            <td>
              {% if request.user|can_add:object or request.user|can_change:object or request.user|can_delete:object %}
              <span id="secret" class="font-monospace" data-secret="{{ object.parameters|get_key:name }}">{{
                object.parameters|get_key:name|placeholder }}</span>
              <button type="button" class="btn btn-sm btn-primary toggle-secret float-end" data-bs-toggle="button">Show
                Secret</button>
              {% else %}
              <i>Password Hidden</i>
              {% endif %}
            </td>
            {% else %}
            <td>{{ object.parameters|get_key:name|placeholder }}</td>
            {% endif %}
          </tr>
          {% empty %}
          <tr>
            <td colspan="2" class="text-muted">
              No parameters defined
            </td>
          </tr>
          {% endfor %}
        </table>
      </div>
    </div>
    {% include 'inc/panels/related_objects.html' %}
    {% include 'inc/panels/custom_fields.html' %}
    {% plugin_right_page object %}
  </div>
  {% if job %}
  <div class="col col-md-12" {% if not object.job.completed %} hx-trigger="every 5s" hx-target="#sync_logs"
    hx-select="#sync_logs" hx-select-oob="#sync_status:innerHTML" hx-swap="innerHTML" {% endif %}>
    <div id="sync_logs">{% include 'ipfabric_netbox/partials/job_logs.html' with job=job %}</div>
  </div>
  {% endif %}
</div>
{% endblock %}

ipfabric_netbox/templates/ipfabric_netbox/ipfabrictransformmap.html
{% extends 'generic/object.html' %}
{% load static %}
{% load helpers %}
{% load plugins %}
{% load render_table from django_tables2 %}

{% block content %}
<div class="row mb-3">
  <div class="col col-md-6">
    <div class="card">
      <h5 class="card-header">Transform Map Information</h5>
      <div class="card-body">
        <table class="table table-hover attr-table">
          <tr>
            <th scope="row">Name</th>
            <td>{{ object.name }}</td>
          </tr>
          <tr>
            <th scope="row">Source Model</th>
            <td>ipfabric | {{ object.source_model }}</td>
          </tr>
          <tr>
            <th scope="row">Target Model</th>
            <td>{{ object.target_model }}</td>
          </tr>
          <tr>
            <th scope="row">Status</th>
            <td>{{ object.status }}</td>
          </tr>
          </tr>
        </table>
      </div>
    </div>
    {% plugin_left_page object %}
  </div>
  <div class="col col-md-6">
    {% include 'inc/panels/custom_fields.html' %}
    {% plugin_right_page object %}
  </div>
</div>
{% endblock %}

ipfabric_netbox/templates/ipfabric_netbox/ipfabrictransformmap_list.html
{% extends 'generic/object_list.html' %}

{% block extra_controls %}
<a href="#"
  hx-get="{% url 'plugins:ipfabric_netbox:ipfabrictransformmap_restore' %}"
  hx-target="#htmx-modal-content"
  class="btn btn-warning"
  data-bs-toggle="modal"
  data-bs-target="#htmx-modal"
>
  <span class="mdi mdi-file-restore" aria-hidden="true"></span>&nbsp;Restore
</a>
{% endblock %}

{% block modals %}
  {% include 'inc/htmx_modal.html' %}
{% endblock modals %}